#!/usr/bin/env python3
"""flatwhite — theme generator.

Single source of truth for the flatwhite colorscheme across apps.
Run `python3 build.py` to (re)generate:

  lua/flatwhite/palette.lua        Lua palette table
  kitty/flatwhite.conf             kitty theme
  fish/flatwhite.fish              fish shell colors
  bat/flatwhite.tmTheme            Sublime tmTheme (used by bat / delta)
  assets/palette.svg               palette reference card (README)

Neovim highlight logic lives in lua/flatwhite/init.lua and is NOT
generated — it references the keys defined here.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# --- Palette --------------------------------------------------------------
# name: (hex, "hsl(...) note")  — the hsl note is carried into palette.lua.
PALETTE = {
    "base1":            ("#605A52", "hsl( 34,  8, 35)  main foreground"),
    "base2":            ("#93836C", "hsl( 35, 15, 50)  visual selection bg"),
    "base3":            ("#B9A992", "hsl( 35, 22, 65)  line numbers / comments"),
    "base4":            ("#DCD3C6", "hsl( 35, 24, 82)  sign / fold column"),
    "base5":            ("#E4DDD2", "hsl( 37, 25, 86)  float / statusline bg"),
    "base6":            ("#F1ECE4", "hsl( 37, 32, 92)  statusline (inactive) bg"),
    "base7":            ("#F7F3EE", "hsl( 33, 36, 95)  normal bg"),

    "orange_text":      ("#5B5143", "hsl( 35, 15, 31)"),
    "orange_text_sec":  ("#95805F", "hsl( 36, 22, 48)"),
    "orange_bg":        ("#F7E0C4", "hsl( 33, 77, 87)"),

    "green_text":       ("#525643", "hsl( 73, 12, 30)"),
    "green_text_sec":   ("#81895D", "hsl( 71, 19, 45)"),
    "green_bg":         ("#E3EAC3", "hsl( 70, 48, 84)"),

    "teal_text":        ("#465953", "hsl(161, 12, 31)"),
    "teal_text_sec":    ("#5F8C7D", "hsl(160, 19, 46)"),
    "teal_bg":          ("#D1EBE3", "hsl(161, 39, 87)"),

    "blue_text":        ("#4C5361", "hsl(220, 12, 34)"),
    "blue_text_sec":    ("#7382A0", "hsl(220, 19, 54)"),
    "blue_bg":          ("#DEE5F2", "hsl(220, 45, 91)"),

    "purple_text":      ("#614C61", "hsl(300, 12, 34)"),
    "purple_text_sec":  ("#9C739C", "hsl(300, 17, 53)"),
    "purple_bg":        ("#F2DEF2", "hsl(300, 42, 91)"),

    "diff_add":         ("#2DB448", "hsl(132, 60, 44)"),
    "diff_change":      ("#F2A60D", "hsl( 40, 90, 50)"),
    "diff_change_dark": ("#7A5306", "hsl( 40, 91, 25)"),
    "diff_delete":      ("#FF1414", "hsl(  0,100, 54)"),
    "diff_renamed":     ("#52AEFF", "hsl(208,100, 66)"),

    # A muted red for terminal use — the UI theme has no red text accent.
    "red_text_sec":     ("#C25B5B", "muted red for ANSI"),
}


def c(name):
    return PALETTE[name][0]


# --- nvim/lua/flatwhite/palette.lua ---------------------------------------
def gen_nvim():
    width = max(len(k) for k in PALETTE)
    lines = [
        "-- flatwhite.nvim — light palette",
        "-- GENERATED by ../../build.py — edit build.py and re-run, not this file.",
        "return {",
    ]
    for name, (hexv, note) in PALETTE.items():
        key = (name + " ").ljust(width + 1)
        lines.append(f'  {key}= "{hexv}", -- {note}')
    lines.append("}")
    return "\n".join(lines) + "\n"


# --- kitty/flatwhite.conf --------------------------------------------------
def gen_kitty():
    m = {
        "foreground": c("base1"),
        "background": c("base7"),
        "selection_foreground": c("base6"),
        "selection_background": c("base2"),
        "cursor": c("base1"),
        "cursor_text_color": c("base7"),
        "url_color": c("blue_text_sec"),
        # tabs
        "active_tab_foreground": c("base1"),
        "active_tab_background": c("base5"),
        "inactive_tab_foreground": c("base2"),
        "inactive_tab_background": c("base6"),
    }
    # normal 0-7 then bright 8-15
    ansi = [
        c("base1"),           # 0  black
        c("red_text_sec"),    # 1  red
        c("green_text_sec"),  # 2  green
        c("orange_text_sec"), # 3  yellow
        c("blue_text_sec"),   # 4  blue
        c("purple_text_sec"), # 5  magenta
        c("teal_text_sec"),   # 6  cyan
        c("base4"),           # 7  white
        c("base2"),           # 8  bright black
        c("diff_delete"),     # 9  bright red
        c("diff_add"),        # 10 bright green
        c("diff_change"),     # 11 bright yellow
        c("diff_renamed"),    # 12 bright blue
        c("purple_text"),     # 13 bright magenta
        c("teal_text"),       # 14 bright cyan
        c("base7"),           # 15 bright white
    ]
    out = [
        "# flatwhite — kitty theme",
        "# GENERATED by build.py — edit build.py and re-run, not this file.",
        "",
    ]
    for k, v in m.items():
        out.append(f"{k:<24} {v}")
    out.append("")
    for i, v in enumerate(ansi):
        out.append(f"color{i:<19}{v}")
    return "\n".join(out) + "\n"


# --- fish/flatwhite.fish ---------------------------------------------------
def gen_fish():
    # fish takes hex without the leading '#'.
    def h(name):
        return c(name).lstrip("#")

    # (variable, value, comment) — value may carry --bold / --background=...
    rows = [
        ("fish_color_normal",         h("base1"),                       "base1 — default text"),
        ("fish_color_command",        h("purple_text"),                 "purple_text — command names"),
        ("fish_color_keyword",        h("purple_text"),                 "purple_text — and/or/if/for"),
        ("fish_color_param",          h("base1"),                       "base1 — arguments"),
        ("fish_color_option",         h("orange_text"),                 "orange_text — --flags"),
        ("fish_color_quote",          h("green_text"),                  "green_text — strings"),
        ("fish_color_redirection",    h("teal_text"),                   "teal_text — > | &"),
        ("fish_color_operator",       h("teal_text"),                   "teal_text"),
        ("fish_color_end",            h("base2"),                       "base2 — ; separators"),
        ("fish_color_comment",        h("base3"),                       "base3 — comments"),
        ("fish_color_error",          h("red_text_sec"),                "red_text_sec — invalid input"),
        ("fish_color_autosuggestion", h("base3"),                       "base3 — ghost text"),
        ("fish_color_valid_path",     "--underline",                    "underline valid paths"),
        ("fish_color_selection",      f"--background={h('base4')}",     "base4 — selection bg"),
        ("fish_color_search_match",   f"--background={h('orange_bg')}", "orange_bg — search match bg"),
        ("fish_color_history_current", h("base1") + " --bold",          "base1 — current history item"),
        # completion pager
        ("fish_pager_color_prefix",              h("purple_text") + " --bold", "purple_text — matched prefix"),
        ("fish_pager_color_completion",          h("base1"),                   "base1 — completions"),
        ("fish_pager_color_description",         h("base3"),                   "base3 — descriptions"),
        ("fish_pager_color_selected_background", f"--background={h('base4')}", "base4 — selected row"),
    ]
    var_w = max(len(var) for var, _, _ in rows)
    val_w = max(len(val) for _, val, _ in rows)
    out = [
        "# flatwhite — fish shell colors",
        "# GENERATED by build.py — edit build.py and re-run, not this file.",
        "#",
        "# Install: copy to ~/.config/fish/conf.d/flatwhite.fish (auto-loaded),",
        "# or `source` it from config.fish. `set -g` here shadows any universal",
        "# theme colors set previously via fish_config.",
        "",
    ]
    for var, val, note in rows:
        out.append(f"set -g {var.ljust(var_w)} {val.ljust(val_w)} # {note}")
    return "\n".join(out) + "\n"


# --- bat/flatwhite.tmTheme -------------------------------------------------
def gen_bat():
    def esc(s):
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    def scope(name, sel, fg=None, bg=None, style=None):
        s = ["    <dict>",
             f"      <key>name</key><string>{esc(name)}</string>",
             f"      <key>scope</key><string>{esc(sel)}</string>",
             "      <key>settings</key>",
             "      <dict>"]
        if fg:
            s.append(f"        <key>foreground</key><string>{fg}</string>")
        if bg:
            s.append(f"        <key>background</key><string>{bg}</string>")
        if style:
            s.append(f"        <key>fontStyle</key><string>{style}</string>")
        s += ["      </dict>", "    </dict>"]
        return "\n".join(s)

    scopes = [
        scope("Comment", "comment, punctuation.definition.comment", c("base3"), None, "italic"),
        scope("String", "string, string.quoted, punctuation.definition.string", c("green_text"), c("green_bg")),
        scope("Number", "constant.numeric, constant.numeric.integer, constant.numeric.float", c("base1")),
        scope("Built-in constant", "constant.language, support.constant, constant.other", c("blue_text"), c("blue_bg")),
        scope("Keyword / Storage", "keyword, keyword.control, storage, storage.type, storage.modifier", c("purple_text"), c("purple_bg")),
        scope("Operator", "keyword.operator", c("base1")),
        scope("Function", "entity.name.function, support.function, meta.function-call", c("base1"), None, "bold"),
        scope("Type", "entity.name.type, support.type, storage.type.class, entity.name.class", c("base1")),
        scope("Variable", "variable, variable.other, variable.parameter", c("base1")),
        scope("Namespace / Module", "entity.name.namespace, entity.name.module, support.module, support.other.namespace", c("teal_text"), c("teal_bg")),
        scope("Tag", "entity.name.tag", c("purple_text"), c("purple_bg")),
        scope("Attribute", "entity.other.attribute-name", c("teal_text")),
        scope("Punctuation", "punctuation.separator, punctuation.terminator, punctuation.section", c("base1"), None, "bold"),
        scope("Invalid", "invalid, invalid.illegal", c("diff_delete")),
        scope("Markup heading", "markup.heading, markup.heading entity.name", c("base1"), None, "bold"),
        scope("Markup link", "markup.underline.link, string.other.link", c("blue_text_sec"), None, "underline"),
        scope("Markup bold", "markup.bold", c("base1"), None, "bold"),
        scope("Markup italic", "markup.italic", c("base1"), None, "italic"),
        scope("Diff inserted", "markup.inserted", c("diff_add")),
        scope("Diff deleted", "markup.deleted", c("diff_delete")),
        scope("Diff changed", "markup.changed", c("diff_change_dark")),
    ]
    header = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>flatwhite</string>
  <key>uuid</key>
  <string>b7f9c3a1-4e2d-4a6f-9c1b-flatwhite0001</string>
  <key>comment</key>
  <string>GENERATED by build.py — edit build.py and re-run, not this file.</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key><string>{c("base7")}</string>
        <key>foreground</key><string>{c("base1")}</string>
        <key>caret</key><string>{c("base1")}</string>
        <key>invisibles</key><string>{c("base4")}</string>
        <key>lineHighlight</key><string>{c("base6")}</string>
        <key>selection</key><string>{c("base4")}</string>
        <key>gutter</key><string>{c("base7")}</string>
        <key>gutterForeground</key><string>{c("base3")}</string>
      </dict>
    </dict>
"""
    footer = "  </array>\n</dict>\n</plist>\n"
    return header + "\n".join(scopes) + "\n" + footer


# --- assets/palette.svg ----------------------------------------------------
def gen_svg():
    """A self-contained palette reference card, rendered inline in the README."""
    W, PAD, GAP = 900, 40, 12
    CW = W - 2 * PAD
    SW_H = 52
    CELL_H = SW_H + 34          # swatch + two text lines
    ROW_GAP = 16

    def lum(hexv):
        r, g, b = (int(hexv[i:i + 2], 16) / 255 for i in (1, 3, 5))
        f = lambda x: x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4
        return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)

    parts = []
    ink, muted, faint, line = c("base1"), c("base2"), c("base3"), c("base4")

    def swatch(x, y, cw, hexv, label, sub, index=None):
        s = [f'<rect x="{x:.1f}" y="{y}" width="{cw:.1f}" height="{SW_H}" rx="8" '
             f'fill="{hexv}" stroke="rgba(46,42,36,0.14)"/>']
        if index is not None:
            tc = "rgba(46,42,36,0.82)" if lum(hexv) > 0.42 else "rgba(247,243,238,0.92)"
            s.append(f'<text x="{x + cw - 8:.1f}" y="{y + 17}" text-anchor="end" '
                     f'font-size="11" font-weight="700" fill="{tc}">{index}</text>')
        s.append(f'<text x="{x + 1:.1f}" y="{y + SW_H + 16}" font-size="11.5" '
                 f'font-weight="600" fill="{ink}">{label}</text>')
        s.append(f'<text x="{x + 1:.1f}" y="{y + SW_H + 30}" font-size="10" '
                 f'fill="{muted}" letter-spacing="0.3">{sub.upper()}</text>')
        return "".join(s)

    def grid(items, cols, y):
        cw = (CW - (cols - 1) * GAP) / cols
        for i, it in enumerate(items):
            col, row = i % cols, i // cols
            x = PAD + col * (cw + GAP)
            cy = y + row * (CELL_H + ROW_GAP)
            parts.append(swatch(x, cy, cw, *it))
        rows = -(-len(items) // cols)
        return y + rows * (CELL_H + ROW_GAP) - ROW_GAP

    def section(title, y):
        parts.append(f'<text x="{PAD}" y="{y}" font-size="11" font-weight="600" '
                     f'letter-spacing="1.6" fill="{ink}">{title}</text>')
        parts.append(f'<line x1="{PAD}" y1="{y + 12}" x2="{W - PAD}" y2="{y + 12}" '
                     f'stroke="{line}"/>')
        return y + 40

    fams = ["orange", "green", "teal", "blue", "purple"]

    y = 74
    parts.append(f'<text x="{PAD}" y="{y}" font-size="34" font-weight="600" '
                 f'letter-spacing="-0.5" fill="{ink}">flatwhite</text>')
    parts.append(f'<text x="{PAD}" y="{y + 22}" font-size="12" fill="{muted}">'
                 f'A flat, warm, light colorscheme &#183; 28 named tokens</text>')
    y += 60

    y = section("NEUTRAL RAMP", y)
    y = grid([(c(k), k, c(k)) for k in
              ("base1", "base2", "base3", "base4", "base5", "base6", "base7")], 7, y)

    y += 46
    y = section("SYNTAX ACCENTS", y)
    accents = ([(c(f + "_text"), f + "_text", c(f + "_text")) for f in fams]
               + [(c(f + "_text_sec"), f + "_text_sec", c(f + "_text_sec")) for f in fams]
               + [(c(f + "_bg"), f + "_bg", c(f + "_bg")) for f in fams])
    y = grid(accents, 5, y)

    y += 46
    y = section("DIFF &#38; VCS", y)
    y = grid([(c(k), k, c(k)) for k in
              ("diff_add", "diff_change", "diff_change_dark",
               "diff_delete", "diff_renamed", "red_text_sec")], 6, y)

    y += 46
    y = section("TERMINAL &#183; ANSI 16", y)
    ansi = [
        ("base1", "black"), ("red_text_sec", "red"), ("green_text_sec", "green"),
        ("orange_text_sec", "yellow"), ("blue_text_sec", "blue"),
        ("purple_text_sec", "magenta"), ("teal_text_sec", "cyan"), ("base4", "white"),
        ("base2", "br black"), ("diff_delete", "br red"), ("diff_add", "br green"),
        ("diff_change", "br yellow"), ("diff_renamed", "br blue"),
        ("purple_text", "br magenta"), ("teal_text", "br cyan"), ("base7", "br white"),
    ]
    y = grid([(c(k), role, c(k), i) for i, (k, role) in enumerate(ansi)], 8, y)

    H = y + PAD
    head = (f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
            f'viewBox="0 0 {W} {H}" font-family="ui-monospace, SFMono-Regular, '
            f'Menlo, Consolas, monospace">\n'
            f'<rect width="{W}" height="{H}" rx="14" fill="{c("base7")}" '
            f'stroke="{line}"/>\n')
    return head + "\n".join(parts) + "\n</svg>\n"


def write(path, content):
    full = os.path.join(HERE, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(content)
    print("wrote", path)


if __name__ == "__main__":
    write("lua/flatwhite/palette.lua", gen_nvim())
    write("kitty/flatwhite.conf", gen_kitty())
    write("fish/flatwhite.fish", gen_fish())
    write("bat/flatwhite.tmTheme", gen_bat())
    write("assets/palette.svg", gen_svg())
