-- flatwhite.nvim — light palette
-- GENERATED by ../../build.py — edit build.py and re-run, not this file.
return {
  base1            = "#605A52", -- hsl( 34,  8, 35)  main foreground
  base2            = "#93836C", -- hsl( 35, 15, 50)  visual selection bg
  base3            = "#B9A992", -- hsl( 35, 22, 65)  line numbers / comments
  base4            = "#DCD3C6", -- hsl( 35, 24, 82)  sign / fold column
  base5            = "#E4DDD2", -- hsl( 37, 25, 86)  float / statusline bg
  base6            = "#F1ECE4", -- hsl( 37, 32, 92)  statusline (inactive) bg
  base7            = "#F7F3EE", -- hsl( 33, 36, 95)  normal bg
  orange_text      = "#5B5143", -- hsl( 35, 15, 31)
  orange_text_sec  = "#95805F", -- hsl( 36, 22, 48)
  orange_bg        = "#F7E0C4", -- hsl( 33, 77, 87)
  green_text       = "#525643", -- hsl( 73, 12, 30)
  green_text_sec   = "#81895D", -- hsl( 71, 19, 45)
  green_bg         = "#E3EAC3", -- hsl( 70, 48, 84)
  teal_text        = "#465953", -- hsl(161, 12, 31)
  teal_text_sec    = "#5F8C7D", -- hsl(160, 19, 46)
  teal_bg          = "#D1EBE3", -- hsl(161, 39, 87)
  blue_text        = "#4C5361", -- hsl(220, 12, 34)
  blue_text_sec    = "#7382A0", -- hsl(220, 19, 54)
  blue_bg          = "#DEE5F2", -- hsl(220, 45, 91)
  purple_text      = "#614C61", -- hsl(300, 12, 34)
  purple_text_sec  = "#9C739C", -- hsl(300, 17, 53)
  purple_bg        = "#F2DEF2", -- hsl(300, 42, 91)
  diff_add         = "#2DB448", -- hsl(132, 60, 44)
  diff_change      = "#F2A60D", -- hsl( 40, 90, 50)
  diff_change_dark = "#7A5306", -- hsl( 40, 91, 25)
  diff_delete      = "#FF1414", -- hsl(  0,100, 54)
  diff_renamed     = "#52AEFF", -- hsl(208,100, 66)
  red_text_sec     = "#C25B5B", -- muted red for ANSI
}
