-- flatwhite.nvim — light palette
-- GENERATED by ../../build.py — edit build.py and re-run, not this file.
return {
  base1            = "#605A52", -- hsl( 34,  8, 35)  main foreground
  base2            = "#766957", -- AA-tuned: comment fg / visual selection bg
  base3            = "#998B79", -- AA-tuned: line numbers (>=3:1 on base7)
  base4            = "#DCD3C6", -- hsl( 35, 24, 82)  sign / fold column
  base5            = "#E4DDD2", -- hsl( 37, 25, 86)  float / statusline bg
  base6            = "#F1ECE4", -- hsl( 37, 32, 92)  statusline (inactive) bg
  base7            = "#F7F3EE", -- hsl( 33, 36, 95)  normal bg
  orange_text      = "#5B5143", -- hsl( 35, 15, 31)
  orange_text_sec  = "#806D51", -- AA on base7 (ANSI yellow)
  orange_bg        = "#F7E0C3", -- hsl( 34, 78, 87)
  green_text       = "#525643", -- hsl( 73, 12, 30)
  green_text_sec   = "#6D734E", -- AA on base7 (ANSI green)
  green_bg         = "#E2E9C1", -- hsl( 69, 46, 84)
  teal_text        = "#465953", -- hsl(161, 12, 31)
  teal_text_sec    = "#51776B", -- AA on base7 (ANSI cyan)
  teal_bg          = "#D2EBE3", -- hsl(160, 40, 87)
  blue_text        = "#4C5361", -- hsl(220, 12, 34)
  blue_text_sec    = "#63708A", -- AA on base7 (ANSI blue)
  blue_bg          = "#DDE4F2", -- hsl(221, 43, 91)
  purple_text      = "#614C61", -- hsl(300, 12, 34)
  purple_text_sec  = "#876487", -- AA on base7 (ANSI magenta)
  purple_bg        = "#F1DDF1", -- hsl(300, 39, 90)
  diff_add         = "#208033", -- AA on base7 (was #2DB448)
  diff_change      = "#F2A60D", -- hsl( 40, 90, 50)
  diff_change_dark = "#795306", -- hsl( 40, 91, 25)
  diff_delete      = "#DE1111", -- AA on base7 (was #FF1414)
  diff_renamed     = "#52AEFF", -- hsl(208,100, 66)
  red_text_sec     = "#B05353", -- AA on base7 (ANSI red)
}
