# flatwhite — fish shell colors
# GENERATED by build.py — edit build.py and re-run, not this file.
#
# Install: copy to ~/.config/fish/conf.d/flatwhite.fish (auto-loaded),
# or `source` it from config.fish. `set -g` here shadows any universal
# theme colors set previously via fish_config.

set -g fish_color_normal                    605A52              # base1 — default text
set -g fish_color_command                   614C61              # purple_text — command names
set -g fish_color_keyword                   614C61              # purple_text — and/or/if/for
set -g fish_color_param                     605A52              # base1 — arguments
set -g fish_color_option                    5B5143              # orange_text — --flags
set -g fish_color_quote                     525643              # green_text — strings
set -g fish_color_redirection               465953              # teal_text — > | &
set -g fish_color_operator                  465953              # teal_text
set -g fish_color_end                       766957              # base2 — ; separators
set -g fish_color_comment                   998B79              # base3 — comments
set -g fish_color_error                     B05353              # red_text_sec — invalid input
set -g fish_color_autosuggestion            998B79              # base3 — ghost text
set -g fish_color_valid_path                --underline         # underline valid paths
set -g fish_color_selection                 --background=DCD3C6 # base4 — selection bg
set -g fish_color_search_match              --background=F7E0C3 # orange_bg — search match bg
set -g fish_color_history_current           605A52 --bold       # base1 — current history item
set -g fish_pager_color_prefix              614C61 --bold       # purple_text — matched prefix
set -g fish_pager_color_completion          605A52              # base1 — completions
set -g fish_pager_color_description         998B79              # base3 — descriptions
set -g fish_pager_color_selected_background --background=DCD3C6 # base4 — selected row
